name = "open-face-site"
compatibility_date = "2024-03-25"

[build]
command = "pnpm pages:build"

[site]
bucket = ".vercel/output/static"

[build.processing]
skip_source_maps = true

[build.processing.css]
bundle = true
minify = true

[env.production]
node_compat = true

[[routes]]
pattern = "/api/.*"
zone_name = "open-face.net"