name = "open-face-site"
compatibility_date = "2024-03-25"

[build]
command = "pnpm build"

[build.processing]
skip_source_maps = true

[build.processing.css]
bundle = true
minify = true

[build.output]
base_path = ".next"
pages_build_output_dir = ".next"

[env.production]
node_compat = true

[[routes]]
pattern = "/api/.*"
zone_name = "open-face.net"