name = "open-face-site"
compatibility_date = "2024-03-25"

[build]
command = "pnpm pages:build"

[site]
bucket = ".next/static"

[env.production]
node_compat = true

[[routes]]
pattern = "/api/.*"
zone_name = "open-face.net"

[build.upload]
format = "modules"
main = "./worker.js"
dir = ".next/server/app"